export const UPDATE_lOGIN_STATUS = 'update_login_status'
export const SET_SONG_INFO = 'set_song_info'
export const SET_IS_PLAYING = 'set_is_playing'
export const SET_DURATION = 'set_duration'
export const SET_CURRENTTIME = 'set_currentTime'
export const SET_LIKE_LIST = 'set_like_list'
export const UPDATE_RECENT_PLAYLIST ='set_recent_playlist'
export const UPDATE_USER_INFO = 'update_user-info'