export const UPDATE_lOGIN_STATUS = 'update_login_status'
export const SET_SONG_INFO = 'set_song_info'
export const SET_IS_PLAYING = 'set_is_playing'
export const SET_DURATION = 'set_duration'
export const SET_CURRENTTIME = 'set_currentTime'